### PR TITLE
Laravel 5.5 compatibility

### PR DESCRIPTION
**Pull request by stevevg**
This PR adds Laravel 5.5 compatibility and package auto-discovery feature.
Moreover, it solves a problem with --pretend flag, which may be present also in the latest release version 5.4.4 with Laravel 5.4 (but I didn't test this likely bug).

### CODE REVIEW

**Comment by edmundluong88** [comment]
Hey @stevevg,

Thanks for the PR! I haven't gotten a chance to update the package to support Laravel 5.5, so this is absolutely fantastic. I took a quick peek and it looks good, but I have a few quick questions before I merge this in:

1. I noticed that this package supports 5.5 but none of the Illuminate packages require 5.5 in the composer.json... Will this work on Laravel 5.5 when you have the 5.5 packages installed? I assume you have tested this yourself, but I thought I'd ask as I have ran into issues with Composer complaining about version conflicts in the past.

2. Any particular reason why the `fire()` methods are renamed to `handle()` in the SeedMigrator commands?

3. I see that you introduced an abstract [Migration](https://github.com/eighty8-ventures/laravel-seeder/pull/5/files#diff-5e569725bde0794960c032a33ea991b7) class that extends the Seeder class. Was there any particular reason for this? As it does extend Seeder, it shouldn't break backwards compatibility (as far as I can tell from reading the code) but it does change the way new Seeders are generated. Just wanted to know the motivation behind this new class.

Thanks again for the PR, best regards.

**Comment by stevevg** [comment]
Hi @edmundluong88,
1. I just added the `~5.4` constraint because, when trying to install in a laravel 5.5 environment, composer complained about the fact that it could not uninstall the 5.5 version and revert to a 5.4 laravel installation. However, I think I should change those lines to "5.5.*" in the PR, especially because: see point 2
2. In Laravel 5.5, `fire()` has been refactored to `handle()` for Commands; from official Laravel upgrade docs:
> Any `fire` methods present on your Artisan commands should be renamed to `handle`.
3. The reason is that, when launching the `php artisan seed --pretend`, there is a call to [Illuminate\Database\Migrations\Migrator::pretendToRun()](https://github.com/laravel/framework/blob/1f6e787be138bc0c0f3ae34b49ecc8f776576f6f/src/Illuminate/Database/Migrations/Migrator.php#L375). This method, calls `getQueries()`, that calls `$migration->getConnection()`. However, since we are not dealing with an extension of the Migration class, but with an extension of a Seeder, the `getConnection()` method is undefined, which results in an exception. 
Thus, in the generated seeder, I needed to both extend the Seeder and the Migration class. Since in PHP multiple inheritance is not possible, I needed to have a "chained" inheritance, and defining a new Migration class solved the problem.
Actually, the Migration class I defined is the same as framework/src/Illuminate/Database/Migrations/Migration.php, but I feared that this class might change in the future, so I preferred to define my own for this package.

If you have other questions or requests for this PR, please ask!

**Comment by edmundluong88** [comment]
Hi @stevevg ,

1. Agreed, I believe the Illuminate packages should using `5.5.*`. This will break backwards compatibility with `5.4` of course, so I think I will be creating separate `5.4` and `5.5` branches to keep the two versions independent of each other, much like how Laravel does it.

2. Makes sense to me!

3. This also makes sense, the only thing I would suggest is renaming your custom `Migration` abstract class to something else to avoid confusion with the Laravel one. Since upgrading this package to `5.5` will break `5.4` backwards compatibility anyways, what I think we might be able to do is merge the [MigratableSeeder](https://github.com/eighty8-ventures/laravel-seeder/blob/master/src/LaravelSeeder/Migration/MigratableSeeder.php) interface that's present in the package with your  abstract class and simply name it `MigratableSeeder`. We can change the `run()` and `down()` calls in the interface into `public abstract function` calls that the inheriting classes are forced to implement.

Let me know what you think. Definitely open to hearing other suggestions as well.

Thanks!

**Comment by stevevg** [comment]
Hi @edmundluong88,
I agree with you about the changes you suggest, I made a new commit following your questions.

At this point, you should definitely create a new branch for `5.5`.

I also added [this part](https://github.com/stevevg/laravel-seeder/blob/8b9f0ea92b719de42cfb42e3b6e9db005c80daaa/src/LaravelSeeder/SeederServiceProvider.php#L39), in order to register commands with Laravel, as per [documentation ](https://laravel.com/docs/5.5/packages#commands), despite I don't know if this addition is useful for this package...

**Comment by edmundluong88** [comment]
Hey @stevevg ,

Thanks for making those changes. I should find some time this weekend to create the 5.5/5.4 branches and merge this in.

**Comment by edmundluong88** [comment]
Merged, thank you for the contribution @stevevg !

**Pull request merged**
